#!/bin/bash
read -p "Replace \"foobar\" with? " foobar
read -p "Replace \"Foobar\" with? " Foobar
read -p "Replace \"FOOBAR\" with? " FOOBAR
echo "Please review:"
echo "Content changes:"
echo -e "foobar\t->\t$foobar\nFoobar\t->\t$Foobar\nFOOBAR\t->\t$FOOBAR"
echo "File name changes:"
for filename in *mod_foobar*;
do
    echo "mv \"$filename\" \"${filename//foobar/$foobar}\""
done
echo "Proceed? "

select yn in "Yes" "No";
do
    case $yn in
        Yes )
            # Find and replace content
            find . -type f -exec sed -i "s/foobar/$foobar/g" {} \;
            find . -type f -exec sed -i "s/Foobar/$Foobar/g" {} \;
            find . -type f -exec sed -i "s/FOOBAR/$FOOBAR/g" {} \;
            
            # Find and replace file names
            for filename in *mod_foobar*;
            do
                mv "$filename" "${filename//foobar/$foobar}"
            done
                
            break;;
        No )
            exit;;
    esac
done
            

